config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  post '/upload' => 'home#upload', as: :upload_image

  get '/oauth2callback' => 'home#oauth2callback', as: :oauth2callback

end

app/models/user.rb
class User < ActiveRecord::Base

  has_attached_file :avatar, styles: {
                               mobile_v: '600x148#',
                               mobile_h: '600x148'
                             }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/models/user_follow.rb
class UserFollow < ActiveRecord::Base
    belongs_to :user_id, class_name: 'User'
    belongs_to :friend_id, class_name: 'User'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include HomeHelper
  before_filter :set_user, :only => [:upload]
  before_filter :set_auth_client, :only => [:index, :oauth2callback]

  def index
    @user = User.new
  end

  def channels_list_by_username(service, part, **params)
    response = service.list_channels(part, params).to_json
    items = JSON.parse(response).fetch("items")

    results = []
    items.each do |item|
      channel = [
        'id' => item.fetch("id"),
        'title' => item.fetch("snippet").fetch("title"),
        'view_count' => item.fetch("statistics").fetch("viewCount")
      ]
      results << channel
    end

    results
  end

  def upload
    @user.name = FFaker::Name.name
    @user.address = FFaker::Address.street_address
    @user.sex = FFaker::Gender.random
    @user.phone = FFaker::PhoneNumber.phone_number
    
    if @user.avatar.present?
      @user.save!
    end

    render :json => { 'data' => @user }
  end

  def oauth2callback
    # Initialize the API
    service = Google::Apis::YoutubeV3::YouTubeService.new
    service.client_options.application_name = 'YouTube Data API Ruby Tests'
    @auth_client.code = params['code']
    @auth_client.fetch_access_token!
    service.authorization = @auth_client

    channels = channels_list_by_username(service, 'snippet,contentDetails,statistics', for_username: 'GoogleDevelopers')

    render :json => { 'data' => channels }
  end

  private
  
  def set_user
    @user = User.create(user_params)
  end

  def set_auth_client
    @auth_client = get_auth_client
    @oauth2_uri = @auth_client.authorization_uri.to_s
  end

  def user_params
    params.require(:user).permit(:avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def get_auth_client
    require 'google/apis/youtube_v3'

    auth_client = Signet::OAuth2::Client.new(
      :authorization_uri => 'https://accounts.google.com/o/oauth2/auth',
      :token_credential_uri =>  'https://www.googleapis.com/oauth2/v3/token',
      :client_id => '1018402081253-eb9of8qgppehjdhtd0c0196d50uqj1gd.apps.googleusercontent.com',
      :client_secret => '3VIIyoPXaS9-KWFhyUalLG74',
      :scope => 'https://www.googleapis.com/auth/youtubepartner',
      :redirect_uri => 'http://localhost:3000/oauth2callback'
    )

    auth_client
  end
end

app/views/home/index.html.slim
= link_to 'Oauth2', @oauth2_uri

= form_for(@user, url: upload_image_path) do |f|
  .form-group
    label for="name"
      | Name
    = f.text_field :name
  .form-group
    label for="avatar"
      | Avatar
    = f.file_field :avatar
  button.btn.btn-primary type="submit" Submit

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-dismissible alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        == render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Rails4 Api'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Rails4 Api'}"
    == stylesheet_link_tag "application", :media => 'all', 'data-turbolinks-track' => 'reload'
    == javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'
    == csrf_meta_tags
  body
    header
      == render 'layouts/navigation'
    main[role="main"]
      == render 'layouts/messages'
      == yield